# Enterprise SQL Proxy System - Helm Chart
# Created: 2025-05-30 05:59:34 UTC by Teeksss
# Version: 2.0.0 Final

apiVersion: v2
name: enterprise-sql-proxy
description: A Helm chart for Enterprise SQL Proxy System v2.0.0
version: 2.0.0
appVersion: "2.0.0"
type: application
keywords:
  - sql
  - proxy
  - database
  - security
  - analytics
  - enterprise
home: https://github.com/teeksss/enterprise-sql-proxy
sources:
  - https://github.com/teeksss/enterprise-sql-proxy
maintainers:
  - name: Teeksss
    email: support@enterprise-sql-proxy.com
    url: https://github.com/teeksss
annotations:
  category: Database
  licenses: MIT
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: prometheus
    version: "23.x.x"
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: "6.x.x"
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled
icon: https://raw.githubusercontent.com/teeksss/enterprise-sql-proxy/main/assets/logo.png